# -*- coding: utf-8 -*-
"""DataPreprocess3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idYyXvxvLGXHOr9MBckU6mMzHMlMOj-C
"""

!pip install librosa audiomentations kaggle -q

from google.colab import drive, files
drive.mount('/content/drive')

# Upload your kaggle.json first
files.upload()  # upload kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d ejlok1/cremad -p /content/crema --unzip

import os, glob, re, random
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

AUDIO_DIR   = "/content/crema/AudioWAV"
SR          = 22050
DURATION    = 3.0       # seconds to pad/trim to
N_MELS      = 128
N_FFT       = 2048
HOP_LENGTH  = 512
MAX_LEN     = 128       # time frames
BATCH_SIZE  = 128      # was 64 — more stable gradients
EPOCHS      = 60
LR          = 5e-4     # was 1e-3 — less aggressive start
NUM_CLASSES = 6

# CREMA-D label map from filename code
LABEL_MAP = {
    "ANG": "angry",
    "DIS": "disgust",
    "FEA": "fear",
    "HAP": "happy",
    "NEU": "neutral",
    "SAD": "sad"
}

import pandas as pd

def parse_cremad_filename(path):
    fname = os.path.basename(path)
    parts = fname.replace(".wav","").split("_")
    # Format: ActorID_SentenceID_Emotion_Intensity
    emotion_code = parts[2]
    return LABEL_MAP.get(emotion_code, None)

audio_files = glob.glob(os.path.join(AUDIO_DIR, "*.wav"))
print(f"Found {len(audio_files)} audio files")

data = []
for f in audio_files:
    label = parse_cremad_filename(f)
    if label:
        data.append({"path": f, "label": label})

df = pd.DataFrame(data)
print(df["label"].value_counts())

def load_audio(path, sr=SR, duration=DURATION):
    """Load and pad/trim audio to fixed length."""
    y, _ = librosa.load(path, sr=sr, duration=duration)
    target_len = int(sr * duration)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)), mode="constant")
    else:
        y = y[:target_len]
    return y

def extract_features(y, sr=SR, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH, max_len=MAX_LEN):
    """
    Returns a (3, n_mels, max_len) array:
      ch0 = mel spectrogram (dB)
      ch1 = delta
      ch2 = delta-delta
    """
    mel = librosa.feature.melspectrogram(
        y=y, sr=sr, n_mels=n_mels, n_fft=n_fft, hop_length=hop_length
    )
    mel_db = librosa.power_to_db(mel, ref=np.max)

    delta  = librosa.feature.delta(mel_db, order=1)
    delta2 = librosa.feature.delta(mel_db, order=2)

    def pad_or_trim(feat):
        if feat.shape[1] < max_len:
            feat = np.pad(feat, ((0,0),(0, max_len - feat.shape[1])), mode="constant")
        return feat[:, :max_len]

    mel_db  = pad_or_trim(mel_db)
    delta   = pad_or_trim(delta)
    delta2  = pad_or_trim(delta2)

    # Normalize each channel to [-1, 1]
    def norm(x):
        mn, mx = x.min(), x.max()
        return (x - mn) / (mx - mn + 1e-8) * 2 - 1

    return np.stack([norm(mel_db), norm(delta), norm(delta2)], axis=0).astype(np.float32)

def augment_audio(y, sr=SR):
    """
    Lighter augmentation — only ONE transform, applied with 50% probability each.
    Preserves clean signal for faster learning.
    """
    # 50% chance of any augmentation at all
    if random.random() < 0.5:
        return y

    def time_shift(y):
        shift = int(sr * random.uniform(-0.1, 0.1))  # reduced from ±200ms to ±100ms
        return np.roll(y, shift)

    def add_noise(y):
        noise_amp = random.uniform(0.001, 0.004) * np.max(np.abs(y))  # halved noise
        return y + noise_amp * np.random.randn(len(y))

    def vol_scale(y):
        return y * random.uniform(0.85, 1.15)  # tighter range

    def pitch_shift(y):
        n_steps = random.uniform(-1.5, 1.5)   # reduced from ±2
        return librosa.effects.pitch_shift(y, sr=sr, n_steps=n_steps)

    fn = random.choice([time_shift, add_noise, vol_scale, pitch_shift])
    try:
        y = fn(y)
    except Exception:
        pass
    return y.astype(np.float32)

class CremaDataset(Dataset):
    def __init__(self, df, augment=False):
        self.paths   = df["path"].tolist()
        self.labels  = df["label_enc"].tolist()
        self.augment = augment

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        y = load_audio(self.paths[idx])
        if self.augment:
            y = augment_audio(y)
        feat = extract_features(y)
        feat = torch.tensor(feat)

        # SpecAugment: only applied 40% of the time, smaller masks
        if self.augment and random.random() < 0.4:
            feat = self._spec_augment(feat)

        return feat, self.labels[idx]

    def _spec_augment(self, feat, F=8, T=12):  # reduced mask sizes
        feat = feat.clone()
        f0 = random.randint(0, N_MELS - F)
        feat[:, f0:f0+F, :] = 0
        t0 = random.randint(0, MAX_LEN - T)
        feat[:, :, t0:t0+T] = 0
        return feat

le = LabelEncoder()
df["label_enc"] = le.fit_transform(df["label"])
print("Classes:", list(le.classes_))

train_df, test_df = train_test_split(df, test_size=0.15, stratify=df["label_enc"], random_state=SEED)
train_df, val_df  = train_test_split(train_df, test_size=0.12, stratify=train_df["label_enc"], random_state=SEED)

print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

train_ds = CremaDataset(train_df, augment=True)
val_ds   = CremaDataset(val_df,   augment=False)
test_ds  = CremaDataset(test_df,  augment=False)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch, pool=True, dropout=0.25):
        super().__init__()
        layers = [
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        ]
        if pool:
            layers.append(nn.MaxPool2d(2, 2))
        layers.append(nn.Dropout2d(dropout))
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)


class EmotionCNN(nn.Module):
    def __init__(self, num_classes=NUM_CLASSES):
        super().__init__()
        # Input: (B, 3, 128, 128)
        self.enc = nn.Sequential(
            ConvBlock(3,   64,  pool=True,  dropout=0.1),   # → (64, 64, 64)
            ConvBlock(64,  128, pool=True,  dropout=0.2),   # → (128, 32, 32)
            ConvBlock(128, 256, pool=True,  dropout=0.25),  # → (256, 16, 16)
            ConvBlock(256, 256, pool=True,  dropout=0.25),  # → (256, 8, 8)
        )
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes),
        )

    def forward(self, x):
        return self.head(self.pool(self.enc(x)))


model = EmotionCNN().to(device)
print("Model re-initialised")
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Parameters: {total_params:,}")

optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="max", patience=3, factor=0.5, min_lr=1e-6
)

def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    total_loss, correct, total = 0.0, 0, 0
    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            if train:
                optimizer.zero_grad()
            logits = model(x)
            loss   = criterion(logits, y)
            if train:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 2.0)
                optimizer.step()
            total_loss += loss.item() * len(y)
            correct    += (logits.argmax(1) == y).sum().item()
            total      += len(y)
    return total_loss / total, correct / total


history = {"train_loss":[], "val_loss":[], "train_acc":[], "val_acc":[]}
best_val_acc, best_state = 0.0, None
patience_counter = 0
MAX_PATIENCE = 15

print(f"{'Epoch':>5} {'TrLoss':>8} {'TrAcc':>7} {'VaLoss':>8} {'VaAcc':>7} {'LR':>10}")
print("-" * 55)

for epoch in range(1, EPOCHS + 1):
    tr_loss, tr_acc = run_epoch(train_loader, train=True)
    va_loss, va_acc = run_epoch(val_loader,   train=False)

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(va_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(va_acc)

    scheduler.step(va_acc)
    current_lr = optimizer.param_groups[0]["lr"]

    if va_acc > best_val_acc:
        best_val_acc = va_acc
        best_state   = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_counter = 0
        tag = " ← best"
    else:
        patience_counter += 1
        tag = f" (patience {patience_counter}/{MAX_PATIENCE})"

    if patience_counter >= MAX_PATIENCE:
        print(f"\nEarly stopping at epoch {epoch}")
        break

    # Print every epoch so you can monitor closely
    print(f"{epoch:>5} {tr_loss:>8.4f} {tr_acc:>7.2%} {va_loss:>8.4f} {va_acc:>7.2%} {current_lr:>10.2e}{tag}")

print(f"\nBest val accuracy: {best_val_acc:.2%}")

import os

save_path = "/content/drive/MyDrive/cremad_efficientnet_best.pth"

torch.save({
    "model_state":    best_state,
    "val_accuracy":   best_val_acc,
    "label_classes":  le.classes_.tolist(),
    "config": {
        "sr":          SR,
        "n_mels":      N_MELS,
        "n_fft":       N_FFT,
        "hop_length":  HOP_LENGTH,
        "max_len":     MAX_LEN,
        "duration":    DURATION,
        "num_classes": NUM_CLASSES,
    }
}, save_path)

print(f"Saved to: {save_path}")
print(f"Best val accuracy: {best_val_acc:.2%}")

from google.colab import files

local_path = "/content/cremad_efficientnet_best.pth"
torch.save({
    "model_state":   best_state,
    "val_accuracy":  best_val_acc,
    "label_classes": le.classes_.tolist(),
    "config": {
        "sr":          SR,
        "n_mels":      N_MELS,
        "n_fft":       N_FFT,
        "hop_length":  HOP_LENGTH,
        "max_len":     MAX_LEN,
        "duration":    DURATION,
        "num_classes": NUM_CLASSES,
    }
}, local_path)

files.download(local_path)  # triggers browser download
print("Download started!")